# Generated by Django 3.1.4 on 2021-01-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField(max_length=30)),
                ('preview', models.IntegerField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
