# Generated by Django 3.1.4 on 2021-01-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_auto_20210101_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='name',
        ),
    ]
