# Generated by Django 3.1.4 on 2021-01-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0011_auto_20210103_2120'),
    ]

    operations = [
        
    ]
